### ISSUE TITLE
Port not customizable

### ISSUE THREAD

**Issue by justinbleach** [rawmind0/alpine-kafka#10]
You cannot specify a port. It will always default to 9092.

**Comment by rawmind0** [comment]
Configurable with env variable ```KAFKA_ADVERTISE_PORT=${KAFKA_ADVERTISE_PORT:-"9092"}	# Port to advertise```

Please, read the README.md, https://github.com/rawmind0/alpine-kafka#default-configuration

**Comment by justinbleach** [comment]
That's the advertise port, that does not allow you to configure what port kafka actually runs on.

**Comment by rawmind0** [comment]
I don't understand you @justinbleach, advertise port is precisely for config what port kafka will listen....

Next line on README.md you could see that the listener is configured using the advertise port ```KAFKA_LISTENER=${KAFKA_LISTENER:-"PLAINTEXT://0.0.0.0:${KAFKA_ADVERTISE_PORT}"}	# Listerner string```
