### ISSUE TITLE
Rancher kafka

### ISSUE THREAD

**Issue by willb0t** [rawmind0/alpine-kafka#11]
I am trying to run your zookeeper and kafka catalog items. Think that the zookeeper is running properly, but kafka not so much.
I am getting this error on loop.
11/17/2017 5:21:45 PM[2017-11-18 01:21:45,718] WARN [Controller id=2, targetBrokerId=3] Connection to node 3 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
11/17/2017 5:21:45 PM[2017-11-18 01:21:45,742] WARN [Controller id=2, targetBrokerId=2] Connection to node 2 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
11/17/2017 5:21:45 PM[2017-11-18 01:21:45,800] WARN [Controller id=2, targetBrokerId=1] Connection to node 1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

on rancher server 1.6 
zookeeper Template Version 3.4.10-rancher1
kafka Template Version 1.0.0-rancher1

**Comment by rawmind0** [comment]
Hi @willb0t, 

Is your rancher system working properly?? It seems you have a network problem mora than a problem with kafka image. Could you ping from one kafka instance to the other ones??

**Comment by rawmind0** [comment]
Close to inactivity. Feel free to reopen if you need.
