### ISSUE TITLE
ADD root  /

### ISSUE THREAD

**Issue by shiMingZheng** [rawmind0/alpine-kafka#15]
What  is 'ADD root /'  means in the Dockerfile ？  If this was added，image was not built with command “docker build -t alpine-kafka:1.0 .”.
I am newer to docker,what should run this image ?

**Comment by rawmind0** [comment]
https://docs.docker.com/engine/reference/builder/#add

Image is already builded, you don't need to build if you are not editing it, you just need to run... 
`docker run <CONFIG_OPTIONS> alpine-kafka:1.0`
https://github.com/rawmind0/alpine-kafka#configuration

**Comment by shiMingZheng** [comment]
Thank you for your reply！I  ignored the root directory where it should be also along with the Dockerfile when image is built。
