### ISSUE TITLE
Update to Kafka 1.1.0

### ISSUE THREAD

**Issue by tmelhiser** [rawmind0/alpine-kafka#16]
Is there a plan/eta to update the image to use Kafka 1.1.0?

Are there any known issues with v1.1.0 and updating the following files to reflect using kafka 1.1.0 :

- version
- Dockerfile

**Comment by rawmind0** [comment]
Updated at commit https://github.com/rawmind0/alpine-kafka/commit/c9eb8680470fc34eb8013c07ced6d19fae1188e8. 

Released rawmind/alpine-kafka:1.1.0-0
